### ISSUE TITLE
loading and storing the trivia questions 

### ISSUE THREAD

**Issue by gideon-maina** [brookatlas/code-jam-6#8]
How do we store the trivia questions and load them to be viewed and answered by the user

- Maybe json ?
- Maybe csv ?
- Maybe an sqlite DB?

**Comment by ScientificGuitar** [comment]
Information that has to be stored is simple enough and small enough to use json instead of sqlite. We'll be going with json for storage and load using python's json package. Commit with a sample template has been made on my branch.
